### PR TITLE
fix for "ValueError: operands could not be broadcast together...

### PR DESCRIPTION
**Pull request by davidweichiang**
fix for "ValueError: operands could not be broadcast together with shapes (3,) (0,)"

I'm not sure how it worked without the fix....different version of PyTorch? (I'm using 1.0.0).

### CODE REVIEW

**Comment by tnq177** [comment]
@davidweichiang as we discussed, this PR is not the fix to the problem. I'll handle empty line when decoding later.

**Comment by davidweichiang** [comment]
b_src_input[i] is an array, right? Does PyTorch allow adding arrays and lists? (Is it possible that my version doesn’t but another version
does?)

**Comment by tnq177** [comment]
b_src_input is a list of lists of different size. I wrap it with numpy.array so that I can do sorting by indices. The code definitely works. The error is caused when we create batch for translation and there's empty (thus empty b_src_input[i]). We can't feed empty input into the model. It doesn't learn to output empty line when it sees empty line. I gotta fix the whole getting translation inputs, decoding, and reconstruct translation along with references in original order pipeline. It's rather messy. But this PR is not the solution.

Right now a simple fix is to make sure every file has no empty line...

**Comment by davidweichiang** [comment]
I definitely still get this error when there are no blank lines in the data, and applying this PR makes the error go away.

**Comment by davidweichiang** [comment]
Does this change break anything for you? If not, I would like to merge, as it doesn't work for me without the change.

**Pull request merged**
